### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hzoo** [hzoo/contributors-on-github#1]
- [x] Upload to the store
  > A detailed description of your application. Write your description to entice users to download your app.
A 128x128 icon to display in the store. You may re-use your app icon here.
At least one 1280x800 or 640x400 screenshot or YouTube video to show off what your app does.
A 440x280 small tile icon that will be displayed on the Chrome Web Store wall.
The primary category where your app should be listed.
Your app's language to help users find it.
  - [x] Icon
- [x] Maybe show the data on other pages/locations?

---
- [x] Follow github's style if possible? http://primercss.io/
- [x] removed repo filtering list (overkill), although maybe a blacklist would be better
- [x] It can easily go on the `issues/3` page [in https://github.com/hzoo/github-contributor-extension/commit/6da58109aac58b1aee445c4489653c2a19c262f8#diff-95ffcbff3c841ad0a802793cabd8940eL152]
- [x] Cleanup
- [ ] Tests
- [ ] Better screenshots
